use_frameworks!

platform :ios, '9.0'

target 'AttributedString_Example' do
  pod 'AttributedString', :path => '../'

  pod 'Toast'
  pod 'Toast-Swift'
  pod 'FLEX', :configurations => ['Debug']
 
#  target 'AttributedString_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
